sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t 121watts/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true 121watts/docker-react yarn test
